modLoader = "lowcodefml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/TechRebornJEI/issues"

[properties]
	"connector:placeholder" = true

[[mods]]
	modId = "techrebornjei"
	version = "0@VERSION@"
	displayName = "TechRebornJEI"
	description = "An addon to Tech Reborn that adds JEI support."
	logoFile = "techrebornjei.logo.png"
	authors = "TheLMiffy1111"

[[dependencies.techrebornjei]]
	modId = "minecraft"
	versionRange = "[1.20,1.20.2)"
	mandatory = true

[[dependencies.techrebornjei]]
	modId = "connectormod"
	versionRange = "*"
	mandatory = true

[[dependencies.techrebornjei]]
	modId = "connectorextras"
	versionRange = "*"
	mandatory = true

[[dependencies.techrebornjei]]
	modId = "jei"
	versionRange = "*"
	mandatory = true

[[dependencies.techrebornjei]]
	modId = "jeidrawables"
	versionRange = "*"
	mandatory = true

[[dependencies.techrebornjei]]
	modId = "techreborn"
	versionRange = "*"
	mandatory = true
